package org.december.beanui.element;

public class Icon {
    public static final String INFO = "el-icon-info";
    public static final String ERROR = "el-icon-error";
    public static final String SUCCESS = "el-icon-success";
    public static final String WARNING = "el-icon-warning";
    public static final String QUESTION = "el-icon-question";
    public static final String BACK = "el-icon-back";
    public static final String ARROW_LEFT = "el-icon-arrow-left";
    public static final String ARROW_DOWN = "el-icon-arrow-down";
    public static final String ARROW_RIGHT = "el-icon-arrow-right";
    public static final String ARROW_UP = "el-icon-arrow-up";
    public static final String CARET_LEFT = "el-icon-caret-left";
    public static final String CARET_BOTTOM = "el-icon-caret-bottom";
    public static final String CARET_TOP = "el-icon-caret-top";
    public static final String CARET_RIGHT = "el-icon-caret-right";
    public static final String D_ARROW_LEFT = "el-icon-d-arrow-left";
    public static final String D_ARROW_RIGHT = "el-icon-d-arrow-right";
    public static final String MINUS = "el-icon-minus";
    public static final String PLUS = "el-icon-plus";
    public static final String REMOVE = "el-icon-remove";
    public static final String CIRCLE_PLUS = "el-icon-circle-plus";
    public static final String REMOVE_OUTLINE = "el-icon-remove-outline";
    public static final String CIRCLE_PLUS_OUTLINE = "el-icon-circle-plus-outline";
    public static final String CLOSE = "el-icon-close";
    public static final String CHECK = "el-icon-check";
    public static final String CIRCLE_CLOS = "el-icon-circle-close";
    public static final String CIRCLE_CHECK = "el-icon-circle-check";
    public static final String CIRCLE_CLOSE_OUTLINE = "el-icon-circle-close-outline";
    public static final String CIRCLE_CHECK_OUTLINE = "el-icon-circle-check-outline";
    public static final String ZOOM_OUT = "el-icon-zoom-out";
    public static final String ZOOM_IN = "el-icon-zoom-in";
    public static final String D_CARET = "el-icon-d-caret";
    public static final String SORT = "el-icon-sort";
    public static final String SORT_DOWN = "el-icon-sort-down";
    public static final String SORT_UP = "el-icon-sort-up";
    public static final String TICKET = "el-icon-tickets";
    public static final String DOCUMENT = "el-icon-document";
    public static final String GOODS = "el-icon-goods";
    public static final String SOLD_OUT = "el-icon-sold-out";
    public static final String NEWS = "el-icon-news";
    public static final String MESSAGE = "el-icon-message";
    public static final String DATE = "el-icon-date";
    public static final String PRINTER = "el-icon-printer";
    public static final String TIME = "el-icon-time";
    public static final String BELL = "el-icon-bell";
    public static final String MOBILE_PHONE = "el-icon-mobile-phone";
    public static final String SERVICE = "el-icon-service";
    public static final String VIEW = "el-icon-view";
    public static final String MENU = "el-icon-menu";
    public static final String MORE = "el-icon-more";
    public static final String MORE_OUTLINE = "el-icon-more-outline";
    public static final String STAR_ON = "el-icon-star-on";
    public static final String STAR_OFF = "el-icon-star-off";
    public static final String LOCATION = "el-icon-location";
    public static final String LOCATION_OUTLINE = "el-icon-location-outline";
    public static final String ICON_PHONE = "el-icon-phone";
    public static final String PHONE_OUTLINE = "el-icon-phone-outline";
    public static final String PICTUR = "el-icon-picture";
    public static final String PICTURE_OUTLINE = "el-icon-picture-outline";
    public static final String DELETE = "el-icon-delete";
    public static final String SEARCH = "el-icon-search";
    public static final String EDIT = "el-icon-edit";
    public static final String EDIT_OUTLINE = "el-icon-edit-outline";
    public static final String RANK = "el-icon-rank";
    public static final String REFRESH = "el-icon-refresh";
    public static final String SHARE = "el-icon-share";
    public static final String SETTING = "el-icon-setting";
    public static final String UPLOAD = "el-icon-upload";
    public static final String UPLOAD2 = "el-icon-upload2";
    public static final String DOWNLOAD = "el-icon-download";
    public static final String LOADING = "el-icon-loading";

    private Icon() {
    }
}
